version: "3"

services:
  postgres:
    image: postgres:13.2
    command: postgres -N 2000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ../../postgres:/var/lib/postgresql/data
    networks:
      - local
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.2
    command: sh -c "redis-server --requirepass password"
    networks:
      - local
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq-custom
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - local

  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - local
    ports:
      - 9200:9200

networks:
  local:
    driver: bridge
